# Generated by Django 3.2.6 on 2021-12-09 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.CharField(blank=True, max_length=255)),
                ('category_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('reorder_level', models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=12)),
                ('reorder_quantity', models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=12)),
                ('item_image', models.ImageField(blank=True, default='item.png', null=True, upload_to='items/')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('added_on', models.DateField(auto_now_add=True)),
                ('sku_number', models.CharField(blank=True, max_length=255, unique=True)),
                ('upc_code', models.CharField(blank=True, max_length=255, unique=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='pos.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='categories', to='pos.store'),
        ),
    ]
