# Generated by Django 3.2.6 on 2021-12-14 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.CharField(blank=True, max_length=255)),
                ('category_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('purchase_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('reorder_level', models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=12)),
                ('reorder_quantity', models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=12)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('item_image', models.ImageField(blank=True, default='item.png', null=True, upload_to='items/')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('added_on', models.DateField(auto_now_add=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='pos.category')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_online_blink', models.BooleanField(default=True)),
                ('dark_mode', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('added_time', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('added_time', models.TimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='pos.item')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('added_time', models.TimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='pos.item')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('KSH', 'CASH'), ('MP', 'MPESA'), ('CHK', 'CHECK')], default='KSH', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('added_time', models.TimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.item')),
            ],
        ),
        migrations.CreateModel(
            name='DeadStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('added_time', models.TimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dead_stock', to='pos.item')),
            ],
        ),
    ]
