# Generated by Django 3.2.6 on 2021-12-09 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='store',
        ),
    ]
