# Generated by Django 3.2.6 on 2021-12-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_item_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='upc_code',
        ),
    ]
