# Generated by Django 3.2.6 on 2021-12-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_auto_20211211_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sku_number',
        ),
    ]
