# Generated by Django 3.2.6 on 2022-01-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='notification',
            name='viewed_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
